# Generated by Django 3.2.9 on 2021-12-24 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_alter_feedback_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 24, 16, 49, 43, 318747), verbose_name='Дата отправки отзыва'),
        ),
    ]
