# Generated by Django 3.2.9 on 2021-12-24 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0011_alter_feedback_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 24, 21, 43, 43, 781284), verbose_name='Дата отправки отзыва'),
        ),
    ]
