# Generated by Django 3.2.9 on 2021-12-24 18:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0013_alter_feedback_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 24, 18, 50, 1, 211634, tzinfo=utc), verbose_name='Дата отправки отзыва'),
        ),
    ]
