# Generated by Django 3.2.9 on 2021-11-20 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_alter_proftest_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='proftest',
            name='question',
            field=models.TextField(null=True),
        ),
        migrations.RemoveField(
            model_name='proftest',
            name='direction',
        ),
        migrations.AddField(
            model_name='proftest',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.directions', verbose_name='Направления'),
        ),
    ]
