# Generated by Django 3.2.9 on 2021-11-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_auto_20211120_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='proftest',
            name='question3',
            field=models.TextField(null=True),
        ),
    ]
