# Generated by Django 3.2.9 on 2021-11-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_proftest_question3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proftest',
            name='question1',
            field=models.TextField(null=True, verbose_name='Первый вопрос'),
        ),
        migrations.AlterField(
            model_name='proftest',
            name='question2',
            field=models.TextField(null=True, verbose_name='Второй вопрос'),
        ),
        migrations.AlterField(
            model_name='proftest',
            name='question3',
            field=models.TextField(null=True, verbose_name='Третий вопрос'),
        ),
    ]
