# Generated by Django 3.2.9 on 2021-11-20 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_auto_20211120_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proftest',
            options={'ordering': ['direction'], 'verbose_name': 'элемент теста', 'verbose_name_plural': 'Профориентационный тест'},
        ),
    ]
