# Generated by Django 3.2.9 on 2021-11-22 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0020_alter_proftest_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proftest',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Test', to='bot.directions', verbose_name='Направления'),
        ),
    ]
