# Generated by Django 3.2.9 on 2021-12-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Никнейм пользователя')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='user id')),
            ],
            options={
                'verbose_name': 'ID пользователя',
                'verbose_name_plural': 'ID пользователей',
            },
        ),
        migrations.AlterModelOptions(
            name='chatidadmission',
            options={'verbose_name': 'ID чата', 'verbose_name_plural': 'ID чата по вопросам поступлению'},
        ),
    ]
