# Generated by Django 3.2.9 on 2021-12-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки отзыва'),
        ),
    ]
