# Generated by Django 3.2.9 on 2021-11-11 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directions',
            options={'ordering': ['level', 'direction'], 'verbose_name': 'элемент раздела', 'verbose_name_plural': "Раздел 'Направления подготовки'"},
        ),
        migrations.AddField(
            model_name='passing_scores',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.directions'),
        ),
    ]
