# Generated by Django 3.2.9 on 2021-11-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_proftest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proftest',
            name='direction',
            field=models.ManyToManyField(to='bot.Directions', verbose_name='Вопрос для направления'),
        ),
    ]
