# Generated by Django 3.2.9 on 2021-11-22 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0023_auto_20211122_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatid',
            old_name='chat_name',
            new_name='chat_direction',
        ),
    ]
