# Generated by Django 3.2.9 on 2021-11-30 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0030_alter_proftest_direction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfTest',
        ),
    ]
