# Generated by Django 3.2.9 on 2021-12-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0031_delete_proftest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatIDAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='ID чата')),
            ],
            options={
                'verbose_name': 'ID чата',
                'verbose_name_plural': 'ID чата по поступлению',
            },
        ),
        migrations.RenameModel(
            old_name='ChatID',
            new_name='ChatIDDirections',
        ),
        migrations.AlterModelOptions(
            name='chatiddirections',
            options={'verbose_name': 'ID чата', 'verbose_name_plural': 'ID чатов для вопросов по направлению подготовки'},
        ),
    ]
