# Generated by Django 3.2.9 on 2021-12-10 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0037_auto_20211210_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatIDAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='ID чата')),
            ],
            options={
                'verbose_name': 'ID чата',
                'verbose_name_plural': 'ID чата по поступлению',
            },
        ),
        migrations.CreateModel(
            name='ChatIDDirections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='ID чата')),
                ('chat_direction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot.directions', verbose_name='Чат для направления подготовки:')),
            ],
            options={
                'verbose_name': 'ID чата',
                'verbose_name_plural': 'ID чатов для вопросов по направлению подготовки',
            },
        ),
    ]
