# Generated by Django 3.2.9 on 2021-11-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_rules', models.TextField(verbose_name='Правила приёма')),
                ('submit_doc', models.TextField(verbose_name='Подать документы')),
                ('passing_scores', models.TextField(verbose_name='Проходные баллы')),
                ('number_of_places', models.TextField(verbose_name='Количество мест')),
                ('achievements', models.TextField(verbose_name='Индивидуальные достижения')),
                ('special_rights', models.TextField(verbose_name='Особые права и льготы')),
                ('admission_stat', models.TextField(verbose_name='Статистика приёма')),
                ('enrollment_proc', models.TextField(verbose_name='Порядок зачисления')),
            ],
            options={
                'verbose_name_plural': "Раздел 'Поступление'",
            },
        ),
    ]
