# Generated by Django 3.2.9 on 2021-11-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excursion', models.TextField()),
            ],
            options={
                'verbose_name': 'Элемент раздела',
                'verbose_name_plural': "Раздел 'Об институте'",
            },
        ),
        migrations.AlterModelOptions(
            name='admission',
            options={'verbose_name': 'Элемент раздела', 'verbose_name_plural': "Раздел 'Поступление'"},
        ),
    ]
