# Generated by Django 3.2.9 on 2021-11-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20211109_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='excursion',
            field=models.TextField(verbose_name='Записаться на экскурсию'),
        ),
    ]
