# Generated by Django 3.2.9 on 2021-11-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_about_excursion'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='acquaintance',
            field=models.TextField(blank=True, verbose_name='Знакомство'),
        ),
        migrations.AddField(
            model_name='about',
            name='contacts',
            field=models.TextField(blank=True, verbose_name='Контакты'),
        ),
        migrations.AddField(
            model_name='about',
            name='events',
            field=models.TextField(blank=True, verbose_name='Мероприятия'),
        ),
        migrations.AddField(
            model_name='about',
            name='map',
            field=models.TextField(blank=True, verbose_name='Карта'),
        ),
        migrations.AddField(
            model_name='about',
            name='partners_work',
            field=models.TextField(blank=True, verbose_name='Партнёры и трудоустройство'),
        ),
        migrations.AddField(
            model_name='about',
            name='photo',
            field=models.TextField(blank=True, verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='about',
            name='science',
            field=models.TextField(blank=True, verbose_name='Наука и учёба'),
        ),
        migrations.AddField(
            model_name='about',
            name='stud_council',
            field=models.TextField(blank=True, verbose_name='Студсовет'),
        ),
        migrations.AlterField(
            model_name='about',
            name='excursion',
            field=models.TextField(blank=True, verbose_name='Записаться на экскурсию'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='achievements',
            field=models.TextField(blank=True, verbose_name='Индивидуальные достижения'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='admission_rules',
            field=models.TextField(blank=True, verbose_name='Правила приёма'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='admission_stat',
            field=models.TextField(blank=True, verbose_name='Статистика приёма'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='enrollment_proc',
            field=models.TextField(blank=True, verbose_name='Порядок зачисления'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='number_of_places',
            field=models.TextField(blank=True, verbose_name='Количество мест'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='passing_scores',
            field=models.TextField(blank=True, verbose_name='Проходные баллы'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='special_rights',
            field=models.TextField(blank=True, verbose_name='Особые права и льготы'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='submit_doc',
            field=models.TextField(blank=True, verbose_name='Подать документы'),
        ),
    ]
