# Generated by Django 3.2.9 on 2021-11-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20211111_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='num_places',
            options={'ordering': ['direction'], 'verbose_name': 'элемент раздела', 'verbose_name_plural': "Раздел 'Поступление -> Количество мест'"},
        ),
        migrations.AlterModelOptions(
            name='passing_scores',
            options={'ordering': ['direction'], 'verbose_name': 'элемент раздела', 'verbose_name_plural': "Раздел 'Поступление -> Проходные баллы'"},
        ),
    ]
