# Generated by Django 3.2.9 on 2021-11-12 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20211111_1703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admission',
        ),
    ]
