# Generated by Django 3.2.9 on 2021-11-09 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
