# Generated by Django 3.2.9 on 2021-11-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_delete_admission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_rules', models.TextField(blank=True, verbose_name='Правила приёма')),
                ('submit_doc', models.TextField(blank=True, verbose_name='Подать документы')),
                ('achievements', models.TextField(blank=True, verbose_name='Индивидуальные достижения')),
                ('special_rights', models.TextField(blank=True, verbose_name='Особые права и льготы')),
                ('admission_stat', models.TextField(blank=True, verbose_name='Статистика приёма')),
                ('enrollment_proc', models.TextField(blank=True, verbose_name='Порядок зачисления')),
            ],
            options={
                'verbose_name': 'элемент раздела',
                'verbose_name_plural': "Раздел 'Поступление'",
            },
        ),
    ]
