# Generated by Django 3.2.9 on 2021-11-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('bak', 'Бакалавриат')], max_length=3, verbose_name='Уровень подготовки')),
                ('direction', models.CharField(max_length=10, verbose_name='Направление подготовки')),
                ('inf', models.TextField()),
            ],
        ),
    ]
