# Generated by Django 3.2.9 on 2021-11-14 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_admission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='num_places',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pass_score', to='bot.directions', verbose_name='Направление подготовки'),
        ),
    ]
