# Generated by Django 3.2.9 on 2021-11-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_directions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directions',
            name='level',
            field=models.CharField(choices=[('bak', 'Бакалавриат'), ('spec', 'Специалитет'), ('mag', 'Магистратура')], max_length=4, verbose_name='Уровень подготовки'),
        ),
    ]
