# Generated by Django 3.2.9 on 2021-11-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_num_places_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq', models.TextField(blank=True, verbose_name='F.A.Q')),
            ],
            options={
                'verbose_name': 'элемент раздела',
                'verbose_name_plural': "Раздел 'Задать вопрос'",
            },
        ),
    ]
