# Generated by Django 3.2.9 on 2021-11-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directions',
            name='inf',
            field=models.TextField(blank=True, verbose_name='Информация о специальности'),
        ),
    ]
