# Generated by Django 3.2.9 on 2021-11-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_directions_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='directions',
            name='block_bot',
            field=models.CharField(choices=[('direct_of_prepare', 'Направления подготовки'), ('passing_scores', 'Проходные баллы'), ('num_of_places', 'Количество мест')], default='direct_of_prepare', max_length=20, verbose_name='Раздел бота'),
        ),
        migrations.AlterField(
            model_name='directions',
            name='inf',
            field=models.TextField(verbose_name='Информация о специальности'),
        ),
        migrations.AlterField(
            model_name='directions',
            name='level',
            field=models.CharField(choices=[('bak', 'Бакалавриат'), ('spec', 'Специалитет'), ('mag', 'Магистратура')], default='bak', max_length=4, verbose_name='Уровень подготовки'),
        ),
    ]
