# Generated by Django 3.2.9 on 2021-11-09 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_auto_20211109_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directions',
            options={'verbose_name': 'Элемент раздела', 'verbose_name_plural': 'Раздел с направлениями подготовки'},
        ),
        migrations.RenameField(
            model_name='directions',
            old_name='block_bot',
            new_name='section',
        ),
    ]
