# Generated by Django 3.2.9 on 2021-11-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_welcome_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.ManyToManyField(null=True, to='bot.Directions', verbose_name='Вопрос для направления')),
            ],
            options={
                'verbose_name': 'элемент теста',
                'verbose_name_plural': 'Профориентационный тест',
            },
        ),
    ]
