# Generated by Django 3.2.9 on 2021-11-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_auto_20211109_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='map',
            new_name='map_dormitory',
        ),
        migrations.AddField(
            model_name='directions',
            name='name_of_dir',
            field=models.CharField(default='null', max_length=50, verbose_name='Название специальности'),
        ),
    ]
