# Generated by Django 3.2.9 on 2021-11-22 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_auto_20211120_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proftest',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proftest', to='bot.directions', verbose_name='Направления'),
        ),
    ]
