# Generated by Django 3.2.9 on 2021-11-22 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0022_chatid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatid',
            name='chat_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.directions', verbose_name='Чат для направления подготовки:'),
        ),
        migrations.AlterField(
            model_name='num_places',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.directions', verbose_name='Направление подготовки'),
        ),
        migrations.AlterField(
            model_name='proftest',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.directions', verbose_name='Направления'),
        ),
    ]
