# Generated by Django 3.2.9 on 2021-11-22 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0024_rename_chat_name_chatid_chat_direction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatID',
        ),
    ]
