# Generated by Django 3.2.9 on 2021-12-10 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0033_chatidadmission_t'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatidadmission',
            name='t',
        ),
    ]
