# Generated by Django 3.2.9 on 2021-12-10 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0034_remove_chatidadmission_t'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatIDAdmission',
        ),
        migrations.DeleteModel(
            name='ChatIDDirections',
        ),
    ]
